#!/bin/bash

pkgs='ripgrep fzf node'

osx() {
    curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
    echo "$pkgs" | xargs -n 1 -P 1 -I {} brew install {}
}

main() {
    mkdir -p ~/me
    rsync --exclude={"README.md","bootstrap",".git/"} -avh --no-perms . ~
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    vim -E -s -u "~/.vim/vimrc" +PlugInstall +qall
    vim -E +'CocInstall -sync coc-tsserver coc-pyright' +qall
}

read -p "Install native dependencies on OSX? (y/n) " -n 1;
if [[ $REPLY = "y" ]]; then
    printf "\nInstalling native dependencies for osx...\n"
    osx &> /dev/null
    printf "Installed native dependencies!\n"
else
    printf "\nNo action taken\n"
fi;

read -p "Install dotfiles? This may overwrite files, and programs may fail if missing native dependencies (y/n) " -n 1;
if [[ $REPLY = "y" ]]; then
    printf "\nInstalling dotfiles...\n"
    main &> /dev/null
    printf "Installed dotfiles!\n"
else
    printf "\nNo action taken\n"
fi;
