# Generated by dotfiles.sh setup — edit freely after creation
{
  inputs = {
    dotfiles.url = "path:@DOTFILES@";
    nixpkgs.follows = "dotfiles/nixpkgs";
    home-manager.follows = "dotfiles/home-manager";
  };

  outputs =
    { dotfiles, ... }:
    {
      homeConfigurations."@USERNAME@" = dotfiles.mkHome {
        platform = "@PLATFORM@";
        username = "@USERNAME@";
        homeDirectory = "@HOME@";
      };
    };
}
