#!/usr/bin/env bash
# shellcheck disable=SC1091

set -euo pipefail

# Constants
PROFILE_PATH="$HOME/.config/home-manager/home.nix"
ORIGIN="github.com/danbergelt/dotfiles.git"
REPO_LOCATION="$HOME/dotfiles"

# Colors
RED="\033[0;31m"
GREEN="\033[0;32m"
YELLOW="\033[0;33m"
BLUE="\033[1;34m"
NC="\033[0m"

# Inputs
FORCE=
TOKEN=

show_usage() {
  cat <<-EOF

  Usage: setup.sh [options]

  Options:

    -h, --help           Display usage information
    -f, --force          Skip user confirmations
    -t, --token [token]  GitHub API token (for initial setup)
    --get-token          Print the current GitHub API token
    --set-token [token]  Update the GitHub API token
 
EOF
}

abort() {
  >&2 echo -e "${RED}[ERROR]${NC} $1" && exit 1
}

info() {
  echo -e "\n${BLUE}[INFO]${NC} $1"
}

warn() {
  echo -e "\n${YELLOW}[WARN]${NC} $1"
}

# Get the current access token
get_token() {
  local url token

  url="$(git -C "$REPO_LOCATION" remote get-url origin 2>/dev/null)"
  # Get the value between 'https://' and '@' (should be the token)
  token="$(echo "$url" | awk -F 'https://|@' 'NF >= 3 {print $2}')"

  if test -n "$token"; then
    echo "$token"
  else
    return 1
  fi
}

# Set the access token
set_token() {
  local token

  token="$1"

  if test -z "$token"; then
    abort "No access token provided"
  fi

  git -C "$REPO_LOCATION" remote set-url origin "https://$token@$ORIGIN"
}

ask() {
  read -rp "$1 (y/n) " choice
  case "$choice" in
    y|Y) return ;;
    n|N) exit 0 ;;
    *) ask "$1" ;;
  esac
}

# These commands must exist
for cmd in git curl; do
  if ! command -v "$cmd" &> /dev/null; then
    abort "$cmd missing in PATH"
  fi
done

# Parse input
while test $# -ne 0; do
  case "$1" in
    -h|--help) show_usage && exit ;;
    -f|--force) FORCE="true" ;;
    -t|--token) shift; TOKEN="${1:-}" ;;

    # Top-level commands to get/set access token
    --get-token) get_token; exit $? ;;
    --set-token) shift; set_token "${1:-}"; exit ;;

    *) show_usage && abort "Unrecognized argument: $1" ;;
  esac
  shift
done

if test -z "$FORCE"; then
  ask "Bootstrap dotfiles?"
fi

info "Cloning dotfiles repo"
if test -e "$REPO_LOCATION"; then
  echo "$REPO_LOCATION already exists"
else
  git clone "https://$ORIGIN" "$REPO_LOCATION"
  git -C "$REPO_LOCATION" config user.name "danbergelt"
  git -C "$REPO_LOCATION" config user.email "dan@danbergelt.com"
  # A token is required to push changes upstream
  if test -n "$TOKEN"; then
    set_token "$TOKEN"
  else
    warn "No token provided, push access will not be configured"
  fi
fi

info "Installing nix"
if command -v nix &> /dev/null; then
  echo "Nix is already installed"
else
  bash <(curl -L https://nixos.org/nix/install)
fi

source "$HOME/.nix-profile/etc/profile.d/nix.sh"

info "Installing home-manager"
if nix-channel --list | grep -q home-manager; then
  echo "Home-manager is already installed"
else
  hm="https://github.com/nix-community/home-manager/archive/master.tar.gz"
  nix-channel --add "$hm" home-manager
  nix-channel --update
  nix-shell '<home-manager>' -A install
fi

# Inject dotfiles config into home-manager profile
imports="imports = [$REPO_LOCATION];"
if ! grep -q -F "$imports" "$PROFILE_PATH"; then
  anchor="programs.home-manager.enable = true;"
  header="# GENERATED BY DOTFILES SETUP SCRIPT"
  script="s:$anchor:$anchor\n\n  $header\n  $imports:"
  if [[ "$OSTYPE" == "darwin"* ]]; then
    sed -i '' "$script" "$PROFILE_PATH"
  else
    sed -i "$script" "$PROFILE_PATH"
  fi
fi

info "Installing packages"
home-manager switch -b bak

echo -e "${GREEN}All done, please reload your shell${NC}\n"
