" Plugins
call plug#begin('~/.vim/plugged')

Plug 'natebosch/vim-lsc'    " language server
Plug 'agude/vim-eldar'      " color scheme
Plug 'FooSoft/vim-argwrap'  " function argument wrapping
Plug 'Raimondi/delimitMate' " auto-closing pairs
Plug 'junegunn/fzf'         " fzf hookup
Plug 'junegunn/fzf.vim'     " fzf hookup enhancement
Plug 'tpope/vim-commentary' " comment bindings
Plug 'tpope/vim-fugitive'   " git bindings
Plug 'sheerun/vim-polyglot' " syntax highlighting

call plug#end()

" Remappings
nnoremap <space> <nop>
let mapleader=" "

" Theme
colorscheme eldar

" Syntax
syntax on
filetype plugin indent on

" Keyboard
nnoremap <leader>a :ArgWrap<CR>

nnoremap <leader>b <C-o>
nnoremap <leader>d <C-]>

nnoremap <leader>e :echo @%<CR>

nnoremap <leader>ff :GFiles<CR>
nnoremap <leader>fc :Rg<CR>

nmap <leader>gb :Git blame<CR>
nmap <leader>gd :Git diff<CR>
nmap <leader>gs :G<CR>
nmap <leader>gw :Gwrite<CR>

nnoremap <leader>i K

nnoremap <leader>p :set paste!<CR>:set paste?<CR>

nnoremap <leader>t :Lex<CR>

nnoremap <leader>w <C-W>w

nnoremap <C-tab> :tabnew<CR>
nnoremap <tab> :tabn<CR>
nnoremap <S-tab> :tabp<CR>

" Explore mode
let g:netrw_liststyle=3
let g:netrw_banner=0
let g:netrw_winsize=30

" Appearance
set number
set relativenumber
set modelines=0
set ruler
set scrolloff=8

" Spacing/formatting
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
set backspace=indent,eol,start

" Search
set incsearch
set ignorecase

" Interaction
set mouse=a
set autoread
autocmd BufWritePre * call Trim()
fun! Trim()
    let l:save = winsaveview()
    keeppatterns %s/\s\+$//e
    call winrestview(l:save)
endfun

" Language server
let g:lsc_auto_map = {
    \ 'Completion': 'completefunc',
    \ 'ShowHover': v:true,
    \ }
let g:lsc_server_commands = {
    \ 'python': {
    \   'command': 'pylsp',
    \   'log_level': -1,
    \   'suppress_stderr': v:true,
    \ },
    \ 'javascript': 'typescript-language-server --stdio',
    \ 'typescript': 'typescript-language-server --stdio',
    \ }
