NIXPRF=~/.nix-profile/etc/profile.d/nix.sh
[[ -s $NIXPRF ]] && . $NIXPRF

export EDITOR="hx"
export GIT_EDITOR="hx"
export COLORTERM="truecolor"

# Prompt styling
export PS1="\w\[\033[36m\]\$(git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ {\1}/')\[\033[00m\] :: "

alias hm="home-manager"

if command -v fzf-share > /dev/null; then
  . "$(fzf-share)/key-bindings.bash"
  . "$(fzf-share)/completion.bash"
fi

BASHRC=~/.bashrc
[[ -s $BASHRC ]] && . $BASHRC
